// Mock data for risks
  // manually assigned to locationID, would be a coonection to a database
const mockRisks = [

  {
    id: "risk-1",
    title: "Single Point of Failure - Critical Machinery",
    description:
      "Primary injection molding machine has no backup. Failure would halt production across all dependent sites.",
    category: "Operational",
    severity: "critical",
    likelihood: "high",
    impact: 9,
    status: "active",
    locationId: "loc-1",
    lastUpdated: "2026-02-01",
    trend: "stable",
    mitigationPlan:
      "Sourcing backup equipment and establishing redundant production capability at Portland facility. Expected completion Q3 2026.",
    initialSeverity: "critical",
    initialLikelihood: "very-high",
  },
  {
    id: "risk-2",
    title: "Aging HVAC System",
    description:
      "Climate control system is 15 years old and showing signs of deterioration. Temperature fluctuations could affect quality.",
    category: "Operational",
    severity: "high",
    likelihood: "very-high",
    impact: 6,
    status: "monitoring",
    locationId: "loc-1",
    lastUpdated: "2026-01-28",
    trend: "increasing",
    mitigationPlan:
      "Complete HVAC replacement scheduled for April 2026. Increased maintenance frequency in interim.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-3",
    title: "Key Supplier Concentration",
    description:
      "85% of raw materials sourced from single supplier. Supply chain disruption would impact production significantly.",
    category: "Supply Chain",
    severity: "critical",
    likelihood: "medium",
    impact: 8,
    status: "mitigated",
    locationId: "loc-1",
    lastUpdated: "2026-02-05",
    trend: "decreasing",
    mitigationPlan:
      "Qualified two additional suppliers. Now maintaining 45-day inventory buffer. Ongoing supplier diversification program.",
    initialSeverity: "critical",
    initialLikelihood: "very-high",
  },
  {
    id: "risk-4",
    title: "Workforce Skill Gap",
    description:
      "High concentration of critical skills in aging workforce. 40% of senior technicians eligible for retirement within 3 years.",
    category: "Operational",
    severity: "high",
    likelihood: "high",
    impact: 7,
    status: "active",
    locationId: "loc-1",
    lastUpdated: "2026-02-03",
    trend: "stable",
    mitigationPlan:
      "Implementing knowledge transfer program and apprenticeship initiative. Offering retention bonuses for key personnel.",
    initialSeverity: "critical",
    initialLikelihood: "very-high",
  },
  {
    id: "risk-5",
    title: "Environmental Compliance - Wastewater",
    description:
      "New EPA regulations require upgraded wastewater treatment. Non-compliance could result in fines or shutdown.",
    category: "Regulatory",
    severity: "critical",
    likelihood: "very-high",
    impact: 8,
    status: "active",
    locationId: "loc-1",
    lastUpdated: "2026-01-30",
    trend: "increasing",
    mitigationPlan:
      "Treatment system upgrade project initiated. Compliance deadline is August 2026. Currently 60% complete.",
    initialSeverity: "critical",
    initialLikelihood: "very-high",
  },
  {
    id: "risk-6",
    title: "Electrical Infrastructure Capacity",
    description:
      "Power grid capacity at 90%. Limited headroom for production expansion or additional equipment.",
    category: "Operational",
    severity: "medium",
    likelihood: "medium",
    impact: 5,
    status: "monitoring",
    locationId: "loc-1",
    lastUpdated: "2026-02-04",
    trend: "stable",
    initialSeverity: "high",
    initialLikelihood: "high",
  },

  {
    id: "risk-7",
    title: "Cleanroom Contamination Risk",
    description:
      "Recent minor contamination events in Class 100 cleanroom. Could jeopardize medical device certifications.",
    category: "Safety",
    severity: "critical",
    likelihood: "low",
    impact: 10,
    status: "mitigated",
    locationId: "loc-2",
    lastUpdated: "2026-02-02",
    trend: "decreasing",
    mitigationPlan:
      "Enhanced air filtration system installed. Additional training for personnel on contamination protocols. Monthly audits implemented.",
    initialSeverity: "critical",
    initialLikelihood: "high",
  },
  {
    id: "risk-8",
    title: "Precision Equipment Calibration",
    description:
      "CNC machines require quarterly calibration. Any delay in calibration could result in out-of-spec parts.",
    category: "Operational",
    severity: "high",
    likelihood: "medium",
    impact: 7,
    status: "monitoring",
    locationId: "loc-2",
    lastUpdated: "2026-01-25",
    trend: "stable",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-9",
    title: "Specialized Material Shortage",
    description:
      "Titanium alloy supply is limited globally. Lead times have extended from 8 to 16 weeks.",
    category: "Supply Chain",
    severity: "high",
    likelihood: "high",
    impact: 6,
    status: "active",
    locationId: "loc-2",
    lastUpdated: "2026-02-06",
    trend: "increasing",
    mitigationPlan:
      "Increasing inventory levels to 90-day supply. Exploring alternative material specifications with engineering team.",
    initialSeverity: "high",
    initialLikelihood: "medium",
  },
  {
    id: "risk-10",
    title: "Seismic Activity",
    description:
      "Facility located in seismically active zone. Equipment requires seismic anchoring and protection systems.",
    category: "Environmental",
    severity: "high",
    likelihood: "low",
    impact: 9,
    status: "mitigated",
    locationId: "loc-2",
    lastUpdated: "2026-01-15",
    trend: "stable",
    mitigationPlan:
      "All critical equipment now seismically rated and anchored. Emergency response plan updated and staff trained.",
    initialSeverity: "critical",
    initialLikelihood: "medium",
  },

  {
    id: "risk-11",
    title: "Inventory Management System Failure",
    description:
      "Legacy WMS showing instability. System outage could prevent accurate tracking of $50M inventory.",
    category: "Operational",
    severity: "critical",
    likelihood: "medium",
    impact: 8,
    status: "active",
    locationId: "loc-3",
    lastUpdated: "2026-02-05",
    trend: "stable",
    mitigationPlan:
      "WMS replacement project underway. Cloud-based system implementation scheduled for completion May 2026.",
    initialSeverity: "critical",
    initialLikelihood: "high",
  },
  {
    id: "risk-12",
    title: "Temperature Control Zones",
    description:
      "Temperature-sensitive materials stored in zones with aging refrigeration units. Risk of product degradation.",
    category: "Operational",
    severity: "high",
    likelihood: "medium",
    impact: 7,
    status: "monitoring",
    locationId: "loc-3",
    lastUpdated: "2026-01-29",
    trend: "stable",
    mitigationPlan:
      "Zone-by-zone refrigeration upgrade in progress. 40% complete. Additional temperature monitoring sensors deployed.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-13",
    title: "Fire Suppression System Compliance",
    description:
      "Fire suppression system requires modernization to meet current code. Insurance premiums increasing.",
    category: "Safety",
    severity: "critical",
    likelihood: "high",
    impact: 9,
    status: "active",
    locationId: "loc-3",
    lastUpdated: "2026-02-01",
    trend: "increasing",
    mitigationPlan:
      "Full system upgrade approved. Installation begins March 2026. Interim measures include increased inspection frequency.",
    initialSeverity: "critical",
    initialLikelihood: "very-high",
  },
  {
    id: "risk-14",
    title: "Transportation Network Dependency",
    description:
      "Heavy reliance on single interstate highway for inbound/outbound shipments. Road closures cause delays.",
    category: "Supply Chain",
    severity: "medium",
    likelihood: "medium",
    impact: 5,
    status: "monitoring",
    locationId: "loc-3",
    lastUpdated: "2026-01-22",
    trend: "stable",
    initialSeverity: "medium",
    initialLikelihood: "high",
  },
  {
    id: "risk-15",
    title: "Security System Vulnerabilities",
    description:
      "Surveillance and access control systems outdated. Gaps in coverage identified in recent security audit.",
    category: "Safety",
    severity: "high",
    likelihood: "medium",
    impact: 6,
    status: "active",
    locationId: "loc-3",
    lastUpdated: "2026-02-03",
    trend: "stable",
    mitigationPlan:
      "Security system upgrade in procurement phase. Enhanced guard patrols implemented as interim measure.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },

  {
    id: "risk-16",
    title: "Intellectual Property Protection",
    description:
      "Research data access controls need strengthening. Risk of IP theft or unauthorized disclosure.",
    category: "Regulatory",
    severity: "critical",
    likelihood: "low",
    impact: 10,
    status: "mitigated",
    locationId: "loc-4",
    lastUpdated: "2026-01-20",
    trend: "stable",
    mitigationPlan:
      "Implemented zero-trust network architecture. Enhanced encryption and access logging. Regular penetration testing.",
    initialSeverity: "critical",
    initialLikelihood: "high",
  },
  {
    id: "risk-17",
    title: "Testing Equipment Downtime",
    description:
      "Environmental testing chamber has extended lead time for parts. Breakdowns cause project delays.",
    category: "Operational",
    severity: "high",
    likelihood: "medium",
    impact: 6,
    status: "monitoring",
    locationId: "loc-4",
    lastUpdated: "2026-01-27",
    trend: "stable",
    mitigationPlan:
      "Stocking critical spare parts. Evaluating backup testing options with third-party labs.",
    initialSeverity: "critical",
    initialLikelihood: "high",
  },
  {
    id: "risk-18",
    title: "Hazardous Materials Handling",
    description:
      "Expanded research into new materials requires upgraded chemical storage and handling procedures.",
    category: "Safety",
    severity: "high",
    likelihood: "medium",
    impact: 7,
    status: "active",
    locationId: "loc-4",
    lastUpdated: "2026-02-04",
    trend: "increasing",
    mitigationPlan:
      "New chemical storage facility under construction. Enhanced safety training program rolled out. EHS specialist hired.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-19",
    title: "Talent Retention - Research Staff",
    description:
      "Competitive market for specialized researchers. High turnover risk impacts project continuity.",
    category: "Financial",
    severity: "medium",
    likelihood: "high",
    impact: 5,
    status: "monitoring",
    locationId: "loc-4",
    lastUpdated: "2026-01-31",
    trend: "stable",
    mitigationPlan:
      "Competitive compensation review completed. Enhanced benefits package. Flexible work arrangements expanded.",
    initialSeverity: "high",
    initialLikelihood: "very-high",
  },
  {
    id: "risk-20",
    title: "Lab Space Capacity",
    description:
      "Current lab space at 95% utilization. Limited room for new projects or expansion of existing programs.",
    category: "Operational",
    severity: "medium",
    likelihood: "high",
    impact: 6,
    status: "active",
    locationId: "loc-4",
    lastUpdated: "2026-02-02",
    trend: "increasing",
    mitigationPlan:
      "Exploring options for expansion or satellite facility. Short-term optimization of existing space underway.",
    initialSeverity: "medium",
    initialLikelihood: "high",
  },
  {
    id: "risk-21",
    title: "Lab Equipment Downtime",
    description:
      "Several critical instruments approaching end-of-life. Increased maintenance windows impacting experiment schedules.",
    category: "Operational",
    severity: "high",
    likelihood: "medium",
    impact: 7,
    status: "active",
    locationId: "loc-5",
    lastUpdated: "2026-02-03",
    trend: "increasing",
    mitigationPlan:
      "Prioritize replacement of top 3 critical instruments; negotiate service contracts to reduce downtime.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-22",
    title: "Skilled Staffing Gap",
    description:
      "Shortage of specialized technicians delaying throughput and extending project timelines.",
    category: "Operational",
    severity: "medium",
    likelihood: "high",
    impact: 6,
    status: "active",
    locationId: "loc-5",
    lastUpdated: "2026-02-04",
    trend: "stable",
    mitigationPlan:
      "Accelerate hiring pipeline; offer retention bonuses and cross-training to cover critical shifts.",
    initialSeverity: "high",
    initialLikelihood: "very-high",
  },
  {
    id: "risk-23",
    title: "Regulatory Audit Findings",
    description:
      "Recent internal pre-audit identified documentation gaps and inconsistent SOP adherence.",
    category: "Compliance",
    severity: "high",
    likelihood: "medium",
    impact: 8,
    status: "active",
    locationId: "loc-5",
    lastUpdated: "2026-02-05",
    trend: "increasing",
    mitigationPlan:
      "Launch corrective action plan; schedule SOP refresher training and close documentation gaps within 30 days.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-24",
    title: "Supply Chain Volatility",
    description:
      "Lead times for key reagents extended by 4–6 weeks, risking schedule slippage.",
    category: "Strategic",
    severity: "medium",
    likelihood: "high",
    impact: 6,
    status: "active",
    locationId: "loc-5",
    lastUpdated: "2026-02-06",
    trend: "increasing",
    mitigationPlan:
      "Qualify secondary suppliers; increase safety stock for top 10 critical materials.",
    initialSeverity: "medium",
    initialLikelihood: "medium",
  },
  {
    id: "risk-25",
    title: "Facilities HVAC Reliability",
    description:
      "Temperature fluctuations in controlled areas observed in the last month, risking sample integrity.",
    category: "Safety",
    severity: "medium",
    likelihood: "medium",
    impact: 5,
    status: "monitoring",
    locationId: "loc-5",
    lastUpdated: "2026-02-05",
    trend: "stable",
    mitigationPlan:
      "Service HVAC chillers; install additional sensors and alerting thresholds; create escalation protocol.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },

  {
    id: "risk-26",
    title: "Manufacturing Throughput Constraint",
    description:
      "Bottleneck at final assembly station causing backlog and missed weekly targets.",
    category: "Operational",
    severity: "high",
    likelihood: "high",
    impact: 7,
    status: "active",
    locationId: "loc-6",
    lastUpdated: "2026-02-03",
    trend: "increasing",
    mitigationPlan:
      "Add parallel assembly line; implement takt-time monitoring and shift realignment.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-27",
    title: "Quality Nonconformance Rate",
    description:
      "Spike in minor defects detected during in-process inspection over the last two sprints.",
    category: "Quality",
    severity: "medium",
    likelihood: "high",
    impact: 6,
    status: "active",
    locationId: "loc-6",
    lastUpdated: "2026-02-04",
    trend: "increasing",
    mitigationPlan:
      "Root cause analysis; reinforce operator training; tighten incoming material inspection.",
    initialSeverity: "medium",
    initialLikelihood: "medium",
  },
  {
    id: "risk-28",
    title: "Critical Spare Availability",
    description:
      "Limited availability of spare parts for key production equipment could extend downtime.",
    category: "Operational",
    severity: "medium",
    likelihood: "medium",
    impact: 5,
    status: "monitoring",
    locationId: "loc-6",
    lastUpdated: "2026-02-06",
    trend: "stable",
    mitigationPlan:
      "Establish min/max spare inventory; formalize vendor consignment agreements.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-29",
    title: "Worker Safety Near Heavy Machinery",
    description:
      "Near-miss incidents increased in the last quarter around high-speed equipment.",
    category: "Safety",
    severity: "high",
    likelihood: "medium",
    impact: 8,
    status: "active",
    locationId: "loc-6",
    lastUpdated: "2026-02-05",
    trend: "increasing",
    mitigationPlan:
      "Reinforce PPE policies; add physical guards; schedule safety stand-down and refreshed training.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-30",
    title: "Energy Cost Exposure",
    description:
      "Unexpected utility cost increases affecting operating margins.",
    category: "Strategic",
    severity: "medium",
    likelihood: "medium",
    impact: 5,
    status: "monitoring",
    locationId: "loc-6",
    lastUpdated: "2026-02-05",
    trend: "stable",
    mitigationPlan:
      "Negotiate utility rate plans; evaluate off-peak scheduling and energy-efficiency retrofits.",
    initialSeverity: "medium",
    initialLikelihood: "high",
  },

  {
    id: "risk-31",
    title: "Research Data Integrity Controls",
    description:
      "Inconsistent data versioning and audit trails for experimental results.",
    category: "Compliance",
    severity: "medium",
    likelihood: "medium",
    impact: 6,
    status: "active",
    locationId: "loc-7",
    lastUpdated: "2026-02-02",
    trend: "stable",
    mitigationPlan:
      "Implement centralized ELN; enforce naming conventions and automated backups with audit logging.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-32",
    title: "IP Protection and Access Controls",
    description:
      "Overly broad access to sensitive project repositories increasing leakage risk.",
    category: "Strategic",
    severity: "high",
    likelihood: "medium",
    impact: 7,
    status: "active",
    locationId: "loc-7",
    lastUpdated: "2026-02-04",
    trend: "increasing",
    mitigationPlan:
      "Tighten role-based access; enable MFA; quarterly access reviews for high-sensitivity projects.",
    initialSeverity: "critical",
    initialLikelihood: "high",
  },
  {
    id: "risk-33",
    title: "Prototype Material Lead Time",
    description:
      "Custom substrates require 5–7 week lead time, creating schedule risk for milestones.",
    category: "Operational",
    severity: "medium",
    likelihood: "high",
    impact: 6,
    status: "active",
    locationId: "loc-7",
    lastUpdated: "2026-02-06",
    trend: "increasing",
    mitigationPlan:
      "Pre-order for milestone gates; identify alternate suppliers; buffer schedule by one sprint.",
    initialSeverity: "medium",
    initialLikelihood: "medium",
  },
  {
    id: "risk-34",
    title: "Lab Safety Compliance Training",
    description:
      "Annual refresher completion rate at 82%, below policy threshold.",
    category: "Safety",
    severity: "medium",
    likelihood: "medium",
    impact: 5,
    status: "active",
    locationId: "loc-7",
    lastUpdated: "2026-02-05",
    trend: "stable",
    mitigationPlan:
      "Mandatory training week; automated reminders; introduce completion KPI in manager dashboards.",
    initialSeverity: "medium",
    initialLikelihood: "high",
  },
  {
    id: "risk-35",
    title: "IT Lab Network Segmentation",
    description:
      "Legacy devices on shared VLANs elevating security risk profile.",
    category: "Compliance",
    severity: "high",
    likelihood: "medium",
    impact: 7,
    status: "active",
    locationId: "loc-7",
    lastUpdated: "2026-02-03",
    trend: "increasing",
    mitigationPlan:
      "Segment critical lab networks; enforce NAC; retire unsupported devices.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },

  {
    id: "risk-36",
    title: "Site Access Control System Latency",
    description:
      "Badge system delays causing entry bottlenecks during shift changes.",
    category: "Operational",
    severity: "medium",
    likelihood: "high",
    impact: 5,
    status: "active",
    locationId: "loc-8",
    lastUpdated: "2026-02-05",
    trend: "increasing",
    mitigationPlan:
      "Upgrade controller firmware; add additional readers; stagger shift start times.",
    initialSeverity: "medium",
    initialLikelihood: "medium",
  },
  {
    id: "risk-37",
    title: "Emergency Response Readiness",
    description:
      "Outdated emergency drill procedures and limited participation in last quarter’s drill.",
    category: "Safety",
    severity: "high",
    likelihood: "medium",
    impact: 8,
    status: "active",
    locationId: "loc-8",
    lastUpdated: "2026-02-04",
    trend: "stable",
    mitigationPlan:
      "Revise emergency plans; schedule full-site drills; coordinate with local authorities.",
    initialSeverity: "critical",
    initialLikelihood: "high",
  },
  {
    id: "risk-38",
    title: "Vendor Contract Renewal Risk",
    description:
      "Key service provider contract expires in 30 days; renewal terms uncertain.",
    category: "Strategic",
    severity: "medium",
    likelihood: "medium",
    impact: 6,
    status: "active",
    locationId: "loc-8",
    lastUpdated: "2026-02-06",
    trend: "increasing",
    mitigationPlan:
      "Engage procurement; define fallback providers; secure bridge agreement to avoid service gap.",
    initialSeverity: "medium",
    initialLikelihood: "high",
  },
  {
    id: "risk-39",
    title: "Environmental Monitoring Compliance",
    description:
      "Missed calibration window for air monitoring sensors in controlled areas.",
    category: "Compliance",
    severity: "medium",
    likelihood: "medium",
    impact: 5,
    status: "monitoring",
    locationId: "loc-8",
    lastUpdated: "2026-02-03",
    trend: "stable",
    mitigationPlan:
      "Schedule immediate recalibration; add automated calendar reminders; audit sensor coverage.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
  {
    id: "risk-40",
    title: "Physical Security Perimeter",
    description:
      "Perimeter cameras have intermittent connectivity; potential blind spots during peak hours.",
    category: "Safety",
    severity: "medium",
    likelihood: "medium",
    impact: 6,
    status: "active",
    locationId: "loc-8",
    lastUpdated: "2026-02-05",
    trend: "stable",
    mitigationPlan:
      "Replace failing PoE injectors; add redundant network paths; expand camera coverage.",
    initialSeverity: "high",
    initialLikelihood: "high",
  },
];